### ISSUE TITLE
Custom Menu Creator

### ISSUE THREAD

**Issue by Straikerinos** [TheDevTec/CraftyServerSystem#2]
Ability to create custom menus using **GUI** API from **TheAPI**

Example:
```yaml
# Id of gui
# Gui can be open via command /cssgui [gui-id] {player}
gui0:
  title: "&cThis is example"
  # Max 6 lines
  # Each line must contain 9 characters
  # Each character represents item in the menu
  lines:
  - "xxxxxxxxx"
  - "x d o s x"
  - "xxxxcxxxx"
  items:
    # https://github.com/TheDevTec/TheAPI/wiki/ItemMaker
    x:
      action: NONE
      item:
        type: "BLACK_STAINED_GLASS_PANE"
        displayName: "&0"
    c:
      # Actions:
      # CLOSE
      # OPEN_MENU(id)
      # USE_ITEM
      # NONE
      action: CLOSE
      item:
        type: "RED_STAINED_GLASS_PANE"
        displayName: "&cClose"
        lore:
        - ""
        - "&7Click to close menu"
        - ""
    o:
      # Do you want to tick (reflesh) item in the menu?
      # No problemo! How often? Min. 1t (t=tick, s=second, m=minute, h=hour, d=day, w=week, mo=month, y=year)
      refleshEvery: 1s
      # If you have "predicate" section in your item
      # You have to specify "placeholder" and "result"
      predicate:
        # Warning! Placeholders are replaced ASYNCHORNOUSLY
        placeholder: "%player_health%"
        # Our condition system
        # Accepts comparing numbers and strings
        # Conditions:
        # <NUMBER (number is higher than placeholder)
        # >NUMBER (number is lower than placeholder)
        # <=NUMBER (number is higher or equal to placeholder)
        # >=NUMBER (number is lower or equal to placeholder)
        # ==OBJECT (object is same as placeholder)
        # =~OBJECT (object is same as placeholder - ignoring size of characters)
        # !=OBJECT (object isn't same as placeholder)
        condition: "<20"
        # Result can be true/false, if you are using our condition system
        # In other hand, you are using result from placeholder, so you'll have to specify
        #  placeholder result, or you can simply add section "_DEFAULT", which will be used if you don't specified placeholder result
        result:
          true:
            action: USE_ITEM
            # https://github.com/TheDevTec/CraftyServerSystem/blob/main/files/cooldowns.yml
            cooldown: healing
            # If you have cooldown, you'll have to specify item in 2 sections!
            # 1# onCooldown
            # 2# canUse
            item:
              onCooldown:
                type: "PLAYER_HEAD"
                head:
                  owner: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWQ0NTJiZmNkYzNlYTE0ZjllNjEyYjFjOTZhYmVmOTdjMTBlOTZjNzExNmVhMmE0YjFhNWRmOGQ0YWExNzJmOSJ9fX0="
                  type: "VALUES"
                # When player is in cooldown, you'll have {time} placeholder which represents remaing cooldown time
                displayName: "&cHeal"
                lore:
                - ""
                - "&7You're in cooldown, you can heal yourself after {time}"
                - ""
              canUse:
                type: "PLAYER_HEAD"
                head:
                  owner: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTZhMTA2YmQ3YzViZDNmZDA2ZDkwOGRmZjFjNzczMjVjNTIxZGM4NzM1YzAxYWFkZTc3N2YwNTY0MjFhZDkyOSJ9fX0="
                  type: "VALUES"
                displayName: "&cHeal"
                lore:
                - ""
                - "&7Click for free heal"
                - ""
                onUse:
                  updateItem: true
                  updateInventory: false
                  commands:
                  - "heal {player}"
                  messages: []
          # Or you can use "_DEFAULT" in this case
          false:
            action: NONE
            # If you don't have cooldown, you're specifying item directly in the item section
            item:
              type: "PLAYER_HEAD"
              head:
                owner: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWUyOGJlYTlkMzkzNzNkMzZlZThmYTQwZWM4M2Y5YzNmY2RkOTMxNzUyMjc3NDNmOWRkMWY3ZTc4ODZiN2VlNSJ9fX0="
                type: "VALUES"
              displayName: "&cHeal yourself"
              lore:
              - ""
              - "&7You are OK!"
              - ""
              onUse:
                commands: []
                messages: []
    d:
      action: USE_ITEM
      # https://github.com/TheDevTec/CraftyServerSystem/blob/main/files/cooldowns.yml
      cooldown: freedia
      refleshEvery: 1s
      item:
        onCooldown:
          type: "PLAYER_HEAD"
          head:
            owner: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2FhMDNmODE3MzQxY2FhNTZmYmZjNmQzZjI4MTFhZGI5ODliNjExNzgxMTYyYzEyYWY0YzU4YWYxOGM1M2M3MiJ9fX0="
            type: "VALUES"
          # When player is in cooldown, you'll have {time} placeholder which represents remaing cooldown time
          displayName: "&bGift claimed"
          lore:
          - ""
          - "&7You have gift already claimed!"
          - "&7You can claim next gift after {time}"
          - ""
        canUse:
          type: "PLAYER_HEAD"
          head:
            owner: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmIxZWM3ZGM3NTMwNjFjYTE3NDQyNGVhNDVjZjk0OTBiMzljZDVkY2NhNDc3ZDEzOGE2MDNlNmJlNzU1ZWM3MiJ9fX0="
            type: "VALUES"
          displayName: "&bClaim gift"
          lore:
          - ""
          - "&7Click to claim free diamond!"
          - ""
      onUse:
        updateItem: true
        updateInventory: false
        commands:
        - "give {player} diamond 1"
        messages: []
    s:
      action: USE_ITEM
      item:
        type: "DIRT"
        displayName: "&6Free dirt"
        lore:
        - ""
        - "&7Click for FREE dirt block!"
        - ""
      onUse:
        commands:
        - "give {player} dirt 1"
        messages: []
```
